test(plasma-temple): grid page spec
sberdevices/plasma pull request #1006
Opened 2021-12-20 17:41 UTC by LamaEats

2021-12-30 11:14 UTC, jabzzy requested changes

2021-12-30 11:14 UTC, jabzzy commented on packages/plasma-temple/src/pages/GridPage/GridPage.component-test.tsx
> +        cy.get('[data-cy="grid-item-card"]')
можно подупростить в будущем это место, чтобы не писать attribute selector каждый раз -- https://docs.cypress.io/guides/references/best-practices#Real-World-Example

2021-12-30 11:14 UTC, jabzzy commented on .github/workflows/cypress-ct.yml
> +      if: ${{ always() }}
зачем ифак, если запускается всегда?

2021-12-30 11:14 UTC, jabzzy commented on cypress/plugins/index.ts
> +                launchOptions.args.push('--disable-dev-shm-usage');
было бы полезно оставить коммент, зачем эти опции

2021-12-30 11:14 UTC, jabzzy commented on packages/plasma-temple/src/pages/GalleryPage/GalleryPage.component-test.tsx
> +                            title: 'Cypress Gallery',
норм что тайтл выглядит прилипшим к галерее?

2021-12-30 11:14 UTC, jabzzy commented on packages/plasma-temple/src/pages/GridPage/GridPage.component-test.tsx
> +    it('trigger infinite scroll', () => {
похожего теста с прокруткой до конца для обычной галереи не хватает

2022-01-10 08:17 UTC, LamaEats commented on packages/plasma-temple/src/pages/GridPage/GridPage.component-test.tsx
> +    it('trigger infinite scroll', () => {
у галереи нет сейчас такой функциональности

2022-01-10 08:18 UTC, LamaEats commented on packages/plasma-temple/src/pages/GalleryPage/GalleryPage.component-test.tsx
> +                            title: 'Cypress Gallery',
в данный момент да, есть задача про исправления верстки

2022-01-10 08:18 UTC, LamaEats commented on .github/workflows/cypress-ct.yml
> +      if: ${{ always() }}
@Yeti-or знает)

2022-01-10 08:20 UTC, LamaEats commented on packages/plasma-temple/src/pages/GalleryPage/GalleryPage.component-test.tsx
> +            );
здесь не хочется вносить правки про галерею, отложу на будущее

2022-01-10 08:54 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1006/

2022-01-13 08:42 UTC, VladislavPetyukevich approved these changes

2022-01-13 10:20 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1006/

2022-01-13 12:22 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1006/

2022-01-13 12:36 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1006/
  ui storybook: http://plasma.sberdevices.ru/pr-1006/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1006/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1006/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1006/temple-storybook/

2022-01-17 14:41 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1006/

2022-01-17 14:57 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1006/
  ui storybook: http://plasma.sberdevices.ru/pr-1006/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1006/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1006/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1006/temple-storybook/

2022-01-19 07:52 UTC, Yeti-or commented on .github/workflows/cypress-ct.yml
> +      if: ${{ always() }}
кстати не помню, может @fanisco  помнит

2022-01-19 12:14 UTC, jabzzy commented on packages/plasma-temple/src/pages/GalleryPage/GalleryPage.component-test.tsx
> +            );
давай тогда тикет заведем :)

2022-01-19 12:15 UTC, jabzzy commented on packages/plasma-temple/src/pages/GridPage/GridPage.component-test.tsx
> +    it('trigger infinite scroll', () => {
если я правильно понял, как она работает, то я просто хочу тест, где она докручивается до конца

2022-01-24 07:50 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1006/

2022-01-24 08:03 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1006/
  ui storybook: http://plasma.sberdevices.ru/pr-1006/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1006/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1006/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1006/temple-storybook/

2022-01-27 07:30 UTC, Yeti-or commented on cypress/config/temple-config.json
> +    "scrollBehavior": false
а на что это влияет?

2022-01-27 07:30 UTC, Yeti-or commented on packages/plasma-temple/src/pages/GridPage/GridPage.component-test.tsx
> +            .click()
а что значит another click ? что ты тут проверяешь ?

2022-01-27 11:45 UTC, LamaEats commented on packages/plasma-temple/src/pages/GridPage/GridPage.component-test.tsx
> +            .click()
один тест как пультом клик через Enter, второй эмулирует простой клик, который при таче срабатывает

2022-01-27 11:45 UTC, LamaEats commented on cypress/config/temple-config.json
> +    "scrollBehavior": false
по умолчанию отключает поведение скролла для всех тестов

2022-01-28 14:21 UTC, jabzzy commented on packages/plasma-temple/src/pages/GridPage/GridPage.component-test.tsx
> +        cy.get('[data-cy="grid-item-card"]')
можно прям готовое взять + получить еще пачку удобных геттеров https://testing-library.com/docs/cypress-testing-library/intro/

2022-01-28 14:22 UTC, jabzzy approved these changes

2022-01-28 14:22 UTC, jabzzy commented on packages/plasma-temple/src/pages/GridPage/GridPage.component-test.tsx
> +            .click()
может прямо в коде и написать это?

2022-02-08 15:47 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1006/
  ui storybook: http://plasma.sberdevices.ru/pr-1006/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1006/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1006/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1006/temple-storybook/

2022-02-09 15:19 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1006/

2022-02-09 17:44 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1006/

2022-02-09 17:58 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1006/
  ui storybook: http://plasma.sberdevices.ru/pr-1006/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1006/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1006/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1006/temple-storybook/

2022-02-09 17:58 UTC, merged