test(plasma-b2c, plasma-web): Add statuses to `Notification` test
sberdevices/plasma pull request #1017
Opened 2021-12-25 09:46 UTC by fanisco

2021-12-25 09:58 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1017/

2021-12-25 10:17 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1017/
  ui storybook: http://plasma.sberdevices.ru/pr-1017/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1017/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1017/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1017/temple-storybook/

2021-12-25 12:53 UTC, didolf-sber requested changes

2021-12-25 12:53 UTC, didolf-sber commented on packages/plasma-web/src/components/Notification/Notification.component-test.tsx
> +        cy.get('button').contains('Закрыть').click();
А в чем тут смысл? Зачем закрывать?

2021-12-27 07:07 UTC, fanisco commented on packages/plasma-web/src/components/Notification/Notification.component-test.tsx
> +        cy.get('button').contains('Закрыть').click();
На следующий прогон не должно быть окон

2021-12-27 07:55 UTC, LamaEats approved these changes

2021-12-27 08:12 UTC, neretin-trike approved these changes

2021-12-27 08:57 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1017/

2021-12-27 09:19 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1017/
  ui storybook: http://plasma.sberdevices.ru/pr-1017/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1017/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1017/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1017/temple-storybook/

2021-12-27 09:26 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1017/

2021-12-27 09:36 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1017/
  ui storybook: http://plasma.sberdevices.ru/pr-1017/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1017/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1017/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1017/temple-storybook/

2021-12-27 09:38 UTC, merged