feat(plasma-core): Make toasts stretch more then 50% of container
sberdevices/plasma pull request #1037
Opened 2022-01-12 15:49 UTC by IArny

Добавил для нотификаций возможность тянуться больше чем на половину экрана 

| Было | Стало |
| ----- | -----|
| <img width="513" alt="изображение" src="https://user-images.githubusercontent.com/42856876/149173148-91cc79fd-135a-4aa8-8ad5-c2d3c237ced9.png"> | <img width="506" alt="изображение" src="https://user-images.githubusercontent.com/42856876/149173714-ca5d1a43-cf44-4c97-bc59-d6b1d5d899b1.png"> |

2022-01-12 16:00 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-12 16:12 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-13 13:06 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-13 13:24 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-14 11:32 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-14 11:40 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-14 12:04 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-14 12:13 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-17 10:19 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-17 10:31 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-18 08:06 UTC, fanisco requested changes

2022-01-18 08:06 UTC, fanisco commented on packages/plasma-b2c/src/components/Toast/Toast.tsx
> +import React from 'react';
Нужно все эти наработки перенести в plasma-core. Переменные нужно убрать, оставить все стилями. Переснять скриншоты придется для всех трех библиотек - web, ui, b2c

2022-01-18 11:30 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-18 11:43 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-18 12:29 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-18 12:42 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-18 13:21 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-18 13:34 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-18 13:39 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-18 13:45 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-18 14:23 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-18 15:25 UTC, fanisco requested changes

2022-01-18 15:25 UTC, fanisco commented on packages/plasma-core/src/components/Toast/ToastController.tsx
> +    }
А почему бы просто в самом руте не указать и не вытаскивать наружу приватный компонент?

2022-01-19 05:09 UTC, neretin-trike commented on packages/plasma-core/src/components/Toast/ToastController.tsx
> +    }
это нужно для того, чтобы тост, используемый без хука и контейнера (https://plasma.sberdevices.ru/pr-1037/b2c-storybook/?path=/story/controls-toast--toast-component) не уезжал в лево за границы экрана

2022-01-19 05:09 UTC, neretin-trike approved these changes

2022-01-24 13:08 UTC, fanisco approved these changes

2022-01-24 13:28 UTC, dakhetov approved these changes

2022-01-24 13:29 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-24 13:45 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-24 13:57 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-24 14:08 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-24 14:52 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-25 07:37 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1037/

2022-01-25 07:46 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1037/
  ui storybook: http://plasma.sberdevices.ru/pr-1037/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1037/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1037/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1037/temple-storybook/

2022-01-25 07:57 UTC, merged