feat(plasma-temple): onStart wait for character
sberdevices/plasma pull request #1176
Opened 2022-04-04 13:46 UTC by VladislavPetyukevich

2022-04-04 13:57 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1176/

2022-04-04 14:11 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1176/
  ui storybook: http://plasma.sberdevices.ru/pr-1176/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1176/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1176/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1176/temple-storybook/

2022-04-04 15:13 UTC, LamaEats requested changes

2022-04-04 15:13 UTC, LamaEats commented on packages/plasma-temple/src/components/PlasmaApp/PlasmaApp.tsx
> +                if (typeof onStart === 'object' && onStart.waitForCharacter && isOnStartNotCalledRef.current) {
ух костыль, может лучше в getInitialProps  внутри Page.lazy будем параметром передавать ассистента?

2022-04-06 11:25 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1176/

2022-04-06 11:41 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1176/
  ui storybook: http://plasma.sberdevices.ru/pr-1176/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1176/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1176/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1176/temple-storybook/

2022-04-06 11:46 UTC, VladislavPetyukevich commented on packages/plasma-temple/src/components/PlasmaApp/PlasmaApp.tsx
> +                if (typeof onStart === 'object' && onStart.waitForCharacter && isOnStartNotCalledRef.current) {
Переделал. onStart по прежнему может ожидать команду. Ассистент передаётся в getInitialProps

2022-04-08 08:16 UTC, VladislavPetyukevich commented on packages/plasma-temple/src/hooks/useInitializeAssistant.ts
>          let removeListener = () => {};
Оставить только это?:
```
const removeListener = assistant.on('data', handleOnData);
return () => removeListener();
```

2022-04-08 09:05 UTC, LamaEats commented on packages/plasma-temple/src/hooks/useInitializeAssistant.ts
>          let removeListener = () => {};
да

2022-04-08 09:43 UTC, VladislavPetyukevich commented on packages/plasma-temple/src/hooks/useInitializeAssistant.ts
>          let removeListener = () => {};
Переделал

2022-04-08 09:43 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1176/

2022-04-08 09:56 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1176/
  ui storybook: http://plasma.sberdevices.ru/pr-1176/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1176/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1176/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1176/temple-storybook/

2022-04-08 10:20 UTC, LamaEats approved these changes

2022-04-08 12:05 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1176/

2022-04-08 12:15 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1176/
  ui storybook: http://plasma.sberdevices.ru/pr-1176/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1176/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1176/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1176/temple-storybook/

2022-04-08 12:44 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1176/

2022-04-08 12:59 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1176/
  ui storybook: http://plasma.sberdevices.ru/pr-1176/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1176/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1176/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1176/temple-storybook/

2022-04-11 09:05 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1176/

2022-04-11 09:24 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1176/
  ui storybook: http://plasma.sberdevices.ru/pr-1176/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1176/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1176/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1176/temple-storybook/

2022-04-11 11:11 UTC, merged