feat(ui): add html autofocus in withAutoFocus hoc
sberdevices/plasma pull request #220
Opened 2021-02-19 07:19 UTC by Kud8

2021-02-19 07:24 UTC, Yeti-or commented on packages/ui/src/hocs/withAutoFocus.tsx
> +    return <Component tabIndex={tabIndex} ref={divRef} autoFocus={htmlAutoFocus} {...(props as P)} />;
А у нас же focus происходит в useEffect зачем понадобилось это изменение?

2021-02-19 07:35 UTC, Kud8 commented on packages/ui/src/hocs/withAutoFocus.tsx
> +    return <Component tabIndex={tabIndex} ref={divRef} autoFocus={htmlAutoFocus} {...(props as P)} />;
Чтобы выставлять на кнопку автофокус при загрузке страницы - иначе надо было бы костылить через state и следить за нажатиями клавиатуры чтобы этот автофокус убрать

2021-02-20 08:17 UTC, fanisco commented on packages/ui/src/hocs/withAutoFocus.tsx
> +    return <Component tabIndex={tabIndex} ref={divRef} autoFocus={htmlAutoFocus} {...(props as P)} />;
@Kud8 решения через useEffect не достаточно? Можешь набросать кейс в каком-нибудь jsfiddle?

2021-02-20 08:53 UTC, Kud8 commented on packages/ui/src/hocs/withAutoFocus.tsx
> +    return <Component tabIndex={tabIndex} ref={divRef} autoFocus={htmlAutoFocus} {...(props as P)} />;
```
    const [hasInitialFocusOnLaunchButton, setHasInitialFocusOnLaunchButton] = useState(true);
    useEffect(() => {
        if (hasInitialFocusOnLaunchButton && step !== 0) {
            setHasInitialFocusOnLaunchButton(false);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [step]);
```
Есть такое решение, но придется отслеживать step и работать с ним. Намного проще выставить флаг htmlAutoFocus и все сразу заработает - не будет лишнего кода. (Step меняется при нажатии в сбербоксе вниз/вверх, но сейчас этим всем управляет спатнав и кроме этого случая в нем нет необходимости)

2021-02-20 09:07 UTC, fanisco commented on packages/ui/src/hocs/withAutoFocus.tsx
> +    return <Component tabIndex={tabIndex} ref={divRef} autoFocus={htmlAutoFocus} {...(props as P)} />;
@Kud8 в коде хока есть такой эффект:
```
useEffect(() => {
    if (autoFocus && divRef.current) {
        divRef.current.focus({ preventScroll });
    }
});
```
Почему он вам не подходит?

2021-02-20 09:31 UTC, Kud8 commented on packages/ui/src/hocs/withAutoFocus.tsx
> +    return <Component tabIndex={tabIndex} ref={divRef} autoFocus={htmlAutoFocus} {...(props as P)} />;
Потому что нельзя поставить autoFocus равным true всегда, иначе только эта кнопка будет всегда в фокусе. Поэтому с useEffect нужно следить за навигацией, управлять ее фокусом и тд.
А нужно поведение, что при входе на страницу кнопка в фокусе и от нее спатнав дальше работает.

2021-02-20 11:06 UTC, Yeti-or requested changes

2021-02-20 11:06 UTC, Yeti-or commented on packages/ui/src/hocs/withAutoFocus.tsx
>      });
кажется это должно решиться добавлением зависимости `[autoFocus, difRef.current]`

2021-02-20 11:30 UTC, Kud8 commented
Решил эту проблему через добавление autoFocus в копмонент кнопки: withAutoFocus((props) => <AppLaunchButton autoFocus {...props} />)
Поэтому закрываю PR

2021-02-20 11:30 UTC, closed without merging