feat(plasma-ui): esm build
sberdevices/plasma pull request #251
Opened 2021-03-16 07:43 UTC by KateKate

Билд esm и cjs с помощью rollup, а именно tsdx - конфигурация, чтобы ручками много не писать.
Папка dist выглядит так:
dist
├── components
├── hocs
├── hooks
├── index.d.ts
├── index.d.ts.map
├── index.js
├── mixins
├── types
├── ui.cjs.development.js
├── ui.cjs.development.js.map
├── ui.cjs.production.min.js
├── ui.cjs.production.min.js.map
├── ui.esm.js
├── ui.esm.js.map
└── utils

6 directories, 9 files

Обратите внимание:
- оставила старый build (`build:tsc`), чтобы не ломать обратную совместимость. import { Component } from '@sberdevices/ui/long/path'. хотя я бы выпилила, ибо оно не надо, и подняла бы major версию (breaking changes). решение за вами
- есть проблема - при первой установку node_modules (npm i) долго выполняется `build:tsdx` (2-4 мин), последующие норм - ~14 сек, я чего-то не знаю в чем проблема - надо разбираться. Пользовалась до этого tsdx/rollup, такое впервые

2021-03-16 08:48 UTC, fanisco commented
@KateKate сделаешь то же самое для `plasma-web`?

2021-03-16 10:24 UTC, Yeti-or requested changes

2021-03-16 10:24 UTC, Yeti-or commented on packages/ui/package.json
> +    "types": "dist/index.d.ts",
@KateKate добавь папку `dist` в секцию `files`

2021-03-16 10:57 UTC, KateKate commented
> @KateKate сделаешь то же самое для `plasma-web`?

ок

2021-03-22 07:23 UTC, KateKate commented
не забыла, в процессе. build:tsdx долго  из-за 'rollup-plugin-typescript2'. если вместо него использовать @rollup/plugin-typescript в разы быстрее. только чего-то tree-shaking стал хуже чуток, разбираюсь. как закончу для всех packages пушну es modules build.

2021-03-28 11:24 UTC, KateKate commented
@Yeti-or @fanisco ребейзить? вы посмотрели, норм?

2021-03-29 05:45 UTC, Yeti-or commented
```
File sizes after gzip:

  80.7 KB (-45.91 KB)  build/static/js/2.257dcf6f.chunk.js
  1.56 KB (-1 B)       build/static/js/3.bcd159c3.chunk.js
  1.17 KB (+2 B)       build/static/js/runtime-main.87457449.js
  832 B (-11 B)        build/static/js/main.3f2691be.chunk.js
  574 B                build/static/css/main.9d5b29c0.chunk.css
```

мне кажется стало сильно лучше, давай это вливать

2021-03-29 05:46 UTC, Yeti-or approved these changes

2021-03-29 10:25 UTC, merged