fix(ui): Использование div вместо img в компоненте Image
sberdevices/plasma pull request #271
Opened 2021-03-31 10:12 UTC by ayymkozb

2021-03-31 11:58 UTC, Yeti-or commented on packages/ui/src/components/Image/Image.tsx
> +const StyledDivImg = styled.div<{ src: string }>`
а причины ?

2021-03-31 12:08 UTC, ayymkozb commented on packages/ui/src/components/Image/Image.tsx
> +const StyledDivImg = styled.div<{ src: string }>`
картинки обрезаются, не удается корректно растянуть

2021-03-31 13:06 UTC, Yeti-or commented on packages/ui/src/components/Image/Image.tsx
> +const StyledDivImg = styled.div<{ src: string }>`
скинь пожалуйста пример

2021-03-31 13:17 UTC, ayymkozb commented on packages/ui/src/components/Image/Image.tsx
> +const StyledDivImg = styled.div<{ src: string }>`
![image](https://user-images.githubusercontent.com/58659398/113150089-5f548600-923c-11eb-9dc8-f8d18d546d92.png)
![image](https://user-images.githubusercontent.com/58659398/113150224-84e18f80-923c-11eb-8d09-8f8fdf715e29.png)
но если передать в placeholder картинку, все хорошо растянется, поэтому подумала добавить div для src тоже

2021-04-12 11:20 UTC, fanisco commented
@ayymkozb
1. отребейзься от `master`
2. добавь пример в storybook с переключателем по пропсу `base`
3. commit message переведи на eng (теперь только так пишем)

2021-04-12 11:22 UTC, fanisco requested changes

2021-04-12 11:22 UTC, fanisco commented on packages/ui/src/components/Image/Image.tsx
> +        base?: 'div' | 'img';
@ayymkozb
1. отребейзься от `master`
2. дополни пример в storybook с переключателем по пропсу `base`
3. commit message переведи на eng (теперь только так пишем)

2021-04-13 07:42 UTC, closed without merging