feat(core): добавлен компонент badge в core
sberdevices/plasma pull request #308
Opened 2021-04-15 09:52 UTC by nyet-ty

Есть желание использовать badge во внутреннем сервисе.

2021-04-15 09:59 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-308/

2021-04-15 11:29 UTC, fanisco requested changes

2021-04-15 11:29 UTC, fanisco commented on packages/plasma-core/src/components/Badge/Badge.tsx
> +        height: '1,5rem',
Запятые разве работают?

2021-04-15 11:29 UTC, fanisco commented on packages/plasma-core/src/components/Badge/index.ts
> +export { Badge, badgeSizes, badgeRootSizes } from './Badge';
В core добавил, но в ui не реэкспортнул, в web то же самое. В showcase добавь пример для web

2021-04-15 11:45 UTC, nyet-ty commented on packages/plasma-core/src/components/Badge/index.ts
> +export { Badge, badgeSizes, badgeRootSizes } from './Badge';
а в них реэкспорт прямо из plasma-core/src/components/Badge делать?

2021-04-15 12:51 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-308/

2021-04-15 13:03 UTC, fanisco commented on packages/plasma-core/src/components/Badge/index.ts
> +export { Badge, badgeSizes, badgeRootSizes } from './Badge';
Да
А в шоукейсе делаешь импорт из соответствующих библиотек
Смотри примеры в таких компонентах, как `Button`, `Checkbox`, `Tabs` и т.д.
Там тоже создаются базовые компоненты в `core`. Потом реэкспортятся в `ui` и `web`. А сторибук в шоукейся уже юзает компоненты из `ui` и `web`. Последнее необходимо для тестов.

2021-04-15 13:15 UTC, nyet-ty commented on packages/plasma-core/src/components/Badge/index.ts
> +export { Badge, badgeSizes, badgeRootSizes } from './Badge';
я похоже примерно так сделал и запушил, посмотри, пожалуйста

2021-04-15 15:08 UTC, fanisco requested changes

2021-04-15 15:08 UTC, fanisco commented on docs/showcase/src/web/Badges.stories.tsx
> +    decorators: [UIStoryDecorator, InSpacingDecorator],
Надо использовать WebStoryDecorator

2021-04-15 15:08 UTC, fanisco commented
@nyet-ty сделай `git rebase` от `origin/master`

2021-04-15 15:38 UTC, nyet-ty commented
@fanisco исправил, сделал ребейз и запушил

2021-04-15 15:44 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-308/

2021-04-16 08:41 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-308/

2021-04-16 08:45 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-308/

2021-04-16 10:30 UTC, fanisco approved these changes
`git fetch && git rebase origin/master`

2021-04-16 10:48 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-308/

2021-04-16 10:48 UTC, merged