chore: add cypress and image snapshot
sberdevices/plasma pull request #315
Opened 2021-04-17 14:01 UTC by OgNellis

2021-04-17 14:09 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/

2021-04-21 08:32 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 08:47 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 09:01 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 09:04 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 09:09 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 09:48 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 09:48 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 11:05 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 11:44 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 11:57 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 14:02 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-21 15:20 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-22 12:14 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-23 07:33 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-23 08:23 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-23 08:26 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-23 08:40 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-23 08:56 UTC, fanisco requested changes

2021-04-23 08:56 UTC, fanisco commented on cypress/integration/plasma-ui/button.spec.ts
> +context('Button', () => {
Давайте имена тестов тоже писать с заглавной буквы. Соответствующий этому тесту компонент `Button`, а не `button`

2021-04-23 11:08 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-23 11:08 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-315/
  http://plasma.sberdevices.ru/web-storybook-pr-315/

2021-04-23 12:01 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-315/
  http://plasma.sberdevices.ru/web-storybook-pr-315/

2021-04-23 12:02 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-23 12:03 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-23 12:06 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-315/
  http://plasma.sberdevices.ru/web-storybook-pr-315/

2021-04-23 12:12 UTC, fanisco approved these changes

2021-04-23 12:29 UTC, Yeti-or approved these changes

2021-04-23 12:29 UTC, Yeti-or commented on .github/workflows/cypress.yml
> +        npx lerna bootstrap
не нужно два раза делать install/bootstrap

2021-04-23 12:29 UTC, Yeti-or commented on cypress/fixtures/example.json
> +{}
Думаю можно удалить

2021-04-23 12:29 UTC, Yeti-or commented on cypress/plugins/index.ts
> +// This example plugins/index.js can be used to load plugins
думаю коммент про example можно выпилить

2021-04-23 12:29 UTC, Yeti-or commented on cypress/support/commands.ts
> +// This example commands.js shows you how to
как и тут

2021-04-23 12:29 UTC, Yeti-or commented on package.json
> +    "cy:accept-diffs": "docker run -it --rm -v $PWD:/e2e -w /e2e -e CYPRESS_updateSnapshots=true -e CYPRESS_BASE_URL=${PUBLIC_URL:-'http://host.docker.internal:6006'} cypress/included:7.1.0 run --bro
Надо в CONTRIBUTING.md про это добавить

2021-04-23 14:04 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-315/
  http://plasma.sberdevices.ru/web-storybook-pr-315/

2021-04-23 14:04 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-315/
  http://plasma.sberdevices.ru/web-pr-315/

2021-04-23 14:16 UTC, merged