feat(plasma-ui): Add new scrollAlign values for Carousel
sberdevices/plasma pull request #317
Opened 2021-04-19 13:39 UTC by NicolaiV

I added two new values for the scrollAlign field. "end" which works symmetrically to the "start" value. And "activeDirection", when used, the active element pulls the window behind it, in the direction towards which there is a scroll

2021-04-20 07:20 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-317/

2021-04-20 08:15 UTC, fanisco requested changes
Продублирую сюда: в сторибуке в примере Basic не заработала карусель - ее постоянно гличит

2021-04-20 08:15 UTC, fanisco requested changes

2021-04-20 08:15 UTC, fanisco commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    if (scrollAlign === 'center' || scrollAlign === 'end' || scrollAlign === 'activeDirection') {
Тут наверно надо немного отрефакторить, слишком запутанный код получается.  Еще надо объединить коммиты

2021-04-20 14:20 UTC, Alisa007 commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    if (scrollAlign === 'center' || scrollAlign === 'end' || scrollAlign === 'activeDirection') {
Может auto вместо activeDirection?

2021-04-21 12:57 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-317/
  http://plasma.sberdevices.ru/web-pr-317/

2021-04-21 12:57 UTC, NicolaiV commented
> Продублирую сюда: в сторибуке в примере Basic не заработала карусель - ее постоянно гличит

Поправил

2021-04-23 11:11 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-317/
  http://plasma.sberdevices.ru/web-pr-317/

2021-04-23 11:13 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-317/
  http://plasma.sberdevices.ru/web-storybook-pr-317/

2021-04-26 11:52 UTC, fanisco approved these changes

2021-04-26 12:38 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +            scrollStart = axis === 'x' ? scroll.scrollLeft : scroll.scrollTop;
можно здесь же const и объявить

2021-04-26 12:42 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    switch (scrollAlign) {
Лучше свитч вынести в отдельную функцию, и возвращать pos.
А здесь вызывать функцию и записывать возвращаемое значение в pos.
Кстати pos хреновое название, не ты автор, но я бы мимо не проходил

2021-04-26 12:43 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +                let prevVisible;
Не нужно объявлять это всё заранее. Чем ближе использование к объявлению, тем лучше код читается

2021-04-26 12:44 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +                switch (scrollAlign) {
Это тоже в отдельную функцию

2021-04-26 12:46 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +                        debouncedOnIndexChange(i);
Учитывая как далеко `i` объявляется, я бы переименовал во что-то более информативное

2021-04-27 12:26 UTC, NicolaiV commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +            scrollStart = axis === 'x' ? scroll.scrollLeft : scroll.scrollTop;
Unexpected lexical declaration in case block.eslintno-case-declarations

Линтер запрещает так делать

2021-04-27 13:28 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-317/
  http://plasma.sberdevices.ru/web-pr-317/

2021-04-27 13:30 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-317/
  http://plasma.sberdevices.ru/web-storybook-pr-317/

2021-04-27 14:27 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    scrollStart: number,
Много аргументов, если никак не сократить, то лучше сделать деструктуризацию, чтобы не запутаться в  порядке аргументов

2021-04-27 14:29 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    itemIndex: number,
Тоже слишком много аргументов, рекомендация та же

2021-04-27 14:30 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +            break;
break  не нужен, если есть return

2021-04-27 14:34 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    const prevVisible = prevEdgeEnd > scrollPos && prevEdge < scrollEdge;
Все эти переменные лучше положить в ближе к месту использования.
Например `itemCenter ` нужен только в `case 'center':`
А остальные только в `case 'activeDirection'`.
В области видимости должен быть только жизненно необходимый набор переменных

2021-04-27 14:36 UTC, NicolaiV commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    const prevVisible = prevEdgeEnd > scrollPos && prevEdge < scrollEdge;
Правило eslintno-case-declarations не даёт определять переменные внутри кейса

2021-04-27 14:37 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    }
Оба свича какие-то слишком громоздкие, слишком большая вложенность, слишком много return. Глаз цепляется, но пока не могу конкретные рекомендации сформулировать

2021-04-27 14:41 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    const prevVisible = prevEdgeEnd > scrollPos && prevEdge < scrollEdge;
Вообще для case многовато логики. Если без свича не обойтись(а его наличие напрягает само собой), то лучше всю логику кейса выносить в функцию, а в кейсе делать только вызов этой функции

2021-04-27 14:47 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +    itemIndex: number,
scrollEdge и можно не передавать, а вычислить тут же на месте из scrollPos и scrollSize, возможно что-то еще можно не передавать

2021-04-28 10:27 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-317/
  http://plasma.sberdevices.ru/web-storybook-pr-317/

2021-04-28 10:28 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-317/
  http://plasma.sberdevices.ru/web-storybook-pr-317/

2021-04-28 10:29 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-317/
  http://plasma.sberdevices.ru/web-pr-317/

2021-04-28 10:29 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-317/
  http://plasma.sberdevices.ru/web-pr-317/

2021-04-28 11:58 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +type PositionModByScrollAlignProps = {
Почему не интерфейс?

2021-04-28 11:59 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +type GetItemSlotProps = {
Тот же вопрос

2021-04-28 12:18 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-317/
  http://plasma.sberdevices.ru/web-storybook-pr-317/

2021-04-28 12:19 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-317/
  http://plasma.sberdevices.ru/web-pr-317/

2021-04-28 12:23 UTC, OgNellis commented on packages/plasma-ui/src/components/Carousel/Carousel.tsx
> +}: GetItemSlotProps) => {
Все еще многовато аргументов. scrollEdge и scrollCenter можно высчитывать внутри функции, а не передавать извне.
```
const scrollEdge = scrollPos + scrollSize;
const scrollCenter = scrollPos + scrollSize / 2;
```

2021-04-28 12:33 UTC, OgNellis approved these changes

2021-04-28 12:43 UTC, merged

2021-04-28 12:44 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-317/
  http://plasma.sberdevices.ru/web-storybook-pr-317/

2021-04-28 12:45 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-317/
  http://plasma.sberdevices.ru/web-pr-317/