add Spinner to plasma-web
sberdevices/plasma pull request #326
Opened 2021-04-23 05:31 UTC by nyet-ty

2021-04-23 11:30 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-326/
  http://plasma.sberdevices.ru/web-pr-326/

2021-04-23 11:31 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-326/
  http://plasma.sberdevices.ru/web-storybook-pr-326/

2021-04-23 11:44 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-326/
  http://plasma.sberdevices.ru/web-pr-326/

2021-04-23 11:44 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-326/
  http://plasma.sberdevices.ru/web-storybook-pr-326/

2021-04-23 15:04 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-326/
  http://plasma.sberdevices.ru/web-pr-326/

2021-04-26 09:48 UTC, fanisco approved these changes

2021-04-26 11:10 UTC, Yeti-or requested changes
Давайте не будем вот так прямо переносить;

1) Предлагаю поменять whiteSVG так чтобы в `stop-color` градиентов стоял цвет: `currentColor` тогда можно будет поставить на через реакт color на svg элемент и spinner будет перекрашивается в нужный цвет;
2) сделать для plasma-web по умолчанию цвет accent из токенов 
3) по хорошему size / color должны быть уже чем number / string  но это можно потом
4) и меня смущает что лишнее svg всегда будет приезжать в web и не использоваться; но это тоже можно потом решить

2021-04-30 13:29 UTC, nyet-ty commented
> Давайте не будем вот так прямо переносить;
> 
> 1. Предлагаю поменять whiteSVG так чтобы в `stop-color` градиентов стоял цвет: `currentColor` тогда можно будет поставить на через реакт color на svg элемент и spinner будет перекрашивается в нужный цвет;
> 2. сделать для plasma-web по умолчанию цвет accent из токенов
> 3. по хорошему size / color должны быть уже чем number / string  но это можно потом
> 4. и меня смущает что лишнее svg всегда будет приезжать в web и не использоваться; но это тоже можно потом решить

@Yeti-or 
насчет `currentColor` не понял: его нужно как переменную задать или просто `stop-color="currentColor"` ?

2021-05-04 14:17 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-326/
  http://plasma.sberdevices.ru/web-storybook-pr-326/

2021-05-04 14:18 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-326/
  http://plasma.sberdevices.ru/web-pr-326/

2021-05-08 17:25 UTC, fanisco commented
Что-то у тебя все контролы одного размера https://5f96ec813d800900227e3b93-pujkvverad.chromatic.com/?path=/story/web-controls-spinner--default

2021-05-14 09:48 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-326/
  http://plasma.sberdevices.ru/web-pr-326/

2021-05-14 09:49 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-326/
  http://plasma.sberdevices.ru/web-storybook-pr-326/

2021-05-14 10:45 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-326/
  http://plasma.sberdevices.ru/web-storybook-pr-326/

2021-05-14 10:46 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-326/
  http://plasma.sberdevices.ru/web-pr-326/

2021-05-14 11:19 UTC, fanisco approved these changes

2021-05-14 14:35 UTC, Yeti-or approved these changes

2021-05-14 14:35 UTC, Yeti-or commented on packages/plasma-core/src/components/Spinner/SpinnerSvg.tsx
> +            fill={`url(#prefix__paint0_linear${id})`}
не совсем понял зачем здесь id нужно; defs же работают только на уровне одного svg элемента ?

2021-05-14 15:51 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-326/
  http://plasma.sberdevices.ru/web-pr-326/

2021-05-14 15:52 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-326/
  http://plasma.sberdevices.ru/web-storybook-pr-326/

2021-05-17 07:38 UTC, fanisco commented on packages/plasma-core/src/components/Spinner/SpinnerSvg.tsx
> +            fill={`url(#prefix__paint0_linear${id})`}
Оказалось, что нет =) Если у одного изображения пропишутся defs на какой-то цвет, то все остальные будут работать именно с этим первым defs

2021-05-17 08:00 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-326/
  http://plasma.sberdevices.ru/web-storybook-pr-326/

2021-05-17 08:03 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-326/
  http://plasma.sberdevices.ru/web-pr-326/

2021-05-17 08:06 UTC, merged