feat: short month name in datepicker
sberdevices/plasma pull request #392
Opened 2021-05-14 14:37 UTC by VladislavPetyukevich

В DatePicker на plasma-ui месяц теперь отображается с коротким названием:
<img width="458" alt="Снимок экрана 2021-05-14 в 17 29 07" src="https://user-images.githubusercontent.com/19724906/118286248-f0c14400-b4da-11eb-82ab-ddeada6996ca.png">

2021-05-14 14:47 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-392/
  http://plasma.sberdevices.ru/web-pr-392/

2021-05-14 14:49 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-392/
  http://plasma.sberdevices.ru/web-storybook-pr-392/

2021-05-17 10:58 UTC, fanisco requested changes

2021-05-17 10:58 UTC, fanisco commented on packages/plasma-ui/src/components/Pickers/SimpleDatePicker.tsx
> +    month: monthShortName,
А как переключить? Добавь, пожалуйста, в packages/plasma-ui/components/Pickers/Pickers.stories

2021-05-18 15:26 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-392/
  http://plasma.sberdevices.ru/web-pr-392/

2021-05-18 15:26 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-392/
  http://plasma.sberdevices.ru/web-storybook-pr-392/

2021-05-20 07:56 UTC, OgNellis commented on packages/plasma-ui/src/components/Pickers/DatePicker.tsx
> +        typeof options.shortMonthName === 'boolean' ? options.shortMonthName : defaultOptions.shortMonthName;
Я бы вынес в функцию `typeof options.x === 'boolean' ? options.x : defaultOptions.x;`

2021-05-20 12:51 UTC, VladislavPetyukevich commented on packages/plasma-ui/src/components/Pickers/DatePicker.tsx
> +        typeof options.shortMonthName === 'boolean' ? options.shortMonthName : defaultOptions.shortMonthName;
Исправил

2021-05-21 03:55 UTC, OgNellis commented on packages/plasma-ui/src/components/Pickers/SimpleDatePicker.tsx
> +    const isShortFormat = monthNameFormat && monthNameFormat === 'short';
Первое условие не имеет смысла `monthNameFormat === 'short'` и так проверит что `monthNameFormat` truthy

2021-05-21 04:14 UTC, OgNellis approved these changes

2021-05-24 09:55 UTC, Yeti-or requested changes

2021-05-24 09:55 UTC, Yeti-or commented on packages/plasma-core/src/utils/formatters.ts
> +export const monthShortName = (val: number): string => monthLongName(val).substring(0, 3);
давай так не делать, сравни как выглядит:
```
Array.from(new Array(11)).map((a, i) => new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'long' }).formatToParts(new Date().setMonth(i))[2].value.substring(0, 3))
(11) ["янв", "фев", "мар", "апр", "мая", "июн", "июл", "авг", "сен", "окт", "ноя"]
```

```
Array.from(new Array(11)).map((a, i) => new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'short' }).formatToParts(new Date().setMonth(i))[2].value.slice(0, -1))
(11) ["янв", "февр", "мар", "апр", "ма", "июн", "июл", "авг", "сент", "окт", "нояб"]
```

2021-05-24 09:55 UTC, Yeti-or commented on packages/plasma-ui/src/components/Pickers/DatePicker.tsx
> +        typeof options[key] === 'boolean' ? options[key] : defaultOptions[key];
я что-то не понял почему здесь проверка на typeof ?

2021-05-25 07:11 UTC, VladislavPetyukevich commented on packages/plasma-ui/src/components/Pickers/DatePicker.tsx
> +        typeof options[key] === 'boolean' ? options[key] : defaultOptions[key];
Нужна для того, чтоб седлать тип, значения которого - ключи объекта defaultOptions. Просто мы не можем написать `keyof defaultOptions`, т. к. для `keyof` нужен тип а не значение. Поэтому мы используем `typeof defaultOptions` для того, чтобы получить интерфейс для этого объекта

2021-05-26 11:17 UTC, Yeti-or commented on packages/plasma-ui/src/components/Pickers/DatePicker.tsx
> +        typeof options[key] === 'boolean' ? options[key] : defaultOptions[key];
```
key in options ? options[key] : default[key]
```

2021-05-28 12:14 UTC, Yeti-or approved these changes
Давай вливать

2021-05-31 16:30 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-392/
  http://plasma.sberdevices.ru/web-storybook-pr-392/

2021-05-31 16:31 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-392/
  http://plasma.sberdevices.ru/web-pr-392/

2021-05-31 17:22 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-392/
  http://plasma.sberdevices.ru/web-storybook-pr-392/

2021-05-31 17:24 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-392/
  http://plasma.sberdevices.ru/web-pr-392/

2021-06-01 06:56 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-392/
  http://plasma.sberdevices.ru/web-pr-392/

2021-06-01 06:57 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-392/
  http://plasma.sberdevices.ru/web-storybook-pr-392/

2021-06-01 07:32 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-392/
  http://plasma.sberdevices.ru/web-pr-392/

2021-06-01 07:34 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-392/
  http://plasma.sberdevices.ru/web-storybook-pr-392/

2021-06-01 07:36 UTC, merged