fix(plasma-ui): favicon added
sberdevices/plasma pull request #479
Opened 2021-06-30 10:25 UTC by kayman233

2021-06-30 10:35 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-479/
  http://plasma.sberdevices.ru/web-pr-479/

2021-06-30 10:37 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-479/
  http://plasma.sberdevices.ru/web-storybook-pr-479/

2021-07-01 09:27 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-479/
  http://plasma.sberdevices.ru/web-pr-479/

2021-07-01 09:30 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-479/
  http://plasma.sberdevices.ru/web-storybook-pr-479/

2021-07-01 09:48 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-479/
  http://plasma.sberdevices.ru/web-storybook-pr-479/

2021-07-01 09:51 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-479/
  http://plasma.sberdevices.ru/web-pr-479/

2021-07-04 18:51 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-479/
  http://plasma.sberdevices.ru/web-storybook-pr-479/

2021-07-04 18:51 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-479/
  http://plasma.sberdevices.ru/web-pr-479/

2021-07-04 21:03 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-479/
  http://plasma.sberdevices.ru/web-pr-479/

2021-07-04 21:08 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-479/
  http://plasma.sberdevices.ru/web-storybook-pr-479/

2021-07-05 09:54 UTC, fanisco requested changes

2021-07-05 09:54 UTC, fanisco commented on packages/plasma-ui/.storybook/manager-head.html
> +<link rel='icon' href='sb-favicon.png'/>
Поставь тут двойные кавычки
По ходу у тебя линтер не работает

2021-07-05 09:54 UTC, fanisco commented on packages/plasma-web/.storybook/manager-head.html
> +<link rel='icon' href='sb-favicon.png'/>
Сейм

2021-07-05 11:02 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-479/
  http://plasma.sberdevices.ru/web-pr-479/

2021-07-05 11:03 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-479/
  http://plasma.sberdevices.ru/web-storybook-pr-479/

2021-07-07 09:22 UTC, fanisco approved these changes

2021-07-07 14:49 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-479/
  http://plasma.sberdevices.ru/web-storybook-pr-479/

2021-07-07 14:50 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-479/
  http://plasma.sberdevices.ru/web-pr-479/

2021-07-07 14:51 UTC, merged