Kayman233/feat react17
sberdevices/plasma pull request #496
Opened 2021-07-04 21:26 UTC by kayman233

2021-07-04 21:41 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-496/
  http://plasma.sberdevices.ru/web-pr-496/

2021-07-04 21:43 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-496/
  http://plasma.sberdevices.ru/web-storybook-pr-496/

2021-07-05 23:01 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-496/
  http://plasma.sberdevices.ru/web-storybook-pr-496/

2021-07-05 23:01 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-496/
  http://plasma.sberdevices.ru/web-pr-496/

2021-07-05 23:16 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-496/
  http://plasma.sberdevices.ru/web-storybook-pr-496/

2021-07-05 23:17 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-496/
  http://plasma.sberdevices.ru/web-pr-496/

2021-07-06 12:02 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-496/
  http://plasma.sberdevices.ru/web-pr-496/

2021-07-06 12:02 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-496/
  http://plasma.sberdevices.ru/web-storybook-pr-496/

2021-07-07 08:00 UTC, fanisco commented on .github/workflows/storybook-main.yml
> +
Лишнее вроде

2021-07-07 08:00 UTC, fanisco commented on .github/workflows/tests.yml
> +name: Tests
Зачем этот файл добавлен?

2021-07-07 08:00 UTC, fanisco commented on CONTRIBUTING.md
> +Для корректной работы, необходимо использовать ```node``` версии ```v12.16.1```, а также ```npm``` версии ```6.13.4```.
На мой взгляд, слишком точные версии, может достаточно 12.x и 6.x
@Yeti-or

2021-07-07 08:01 UTC, kayman233 commented on .github/workflows/tests.yml
> +name: Tests
Вася попросил добавить отдельно джобу с тестами

2021-07-08 07:25 UTC, Yeti-or requested changes

2021-07-08 07:25 UTC, Yeti-or commented on CONTRIBUTING.md
> +Для корректной работы, необходимо использовать ```node``` версии ```v12.16.1```, а также ```npm``` версии ```6.13.4```.
Ну в целом да, нужно добавить про то что у нас есть nvm.rc а значит можно просто поставить его

2021-07-08 07:25 UTC, Yeti-or commented on packages/plasma-core/package.json
> +        "react": "16.13.1 || ^17.0.2",
Вот какая версия в итоге поставиться то? 
Если бы я был npm то поставил бы 17
А это значит что все таски мы сейчас гоняем на 17

Нужно чтобы в каком-то воркфлоу явно ставился 17 например в тестах которую добавили
А в остальных гонялся 16

2021-07-08 09:15 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-496/
  http://plasma.sberdevices.ru/web-pr-496/

2021-07-08 09:18 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-496/
  http://plasma.sberdevices.ru/web-storybook-pr-496/

2021-07-09 07:40 UTC, Yeti-or commented on .github/workflows/tests.yml
> +          npx lerna bootstrap
git diff

2021-07-09 07:40 UTC, Yeti-or commented on .github/workflows/tests.yml
> +          npx lerna bootstrap
cat packages/plasma-ui/node_modules/react/package.json

2021-07-12 08:53 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-496/

2021-07-12 14:53 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-496/

2021-07-12 14:55 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-496/
  http://plasma.sberdevices.ru/web-pr-496/

2021-07-12 14:56 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-496/
  http://plasma.sberdevices.ru/web-storybook-pr-496/

2021-07-12 16:20 UTC, Yeti-or requested changes

2021-07-12 16:20 UTC, Yeti-or commented on packages/plasma-ui/package.json
> +        "@mdx-js/react": "1.6.22",
Этого не должно быть в deps
возможно в devDeps но пользователю я не вижу причин этого приносить

2021-07-12 16:21 UTC, Yeti-or commented
Про react-17 действительно все работает как нужно;
можешь отрывать check version
убери только лишнюю зависимость

2021-07-12 17:48 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-496/

2021-07-12 17:51 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-496/
  http://plasma.sberdevices.ru/web-storybook-pr-496/

2021-07-12 17:53 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-496/
  http://plasma.sberdevices.ru/web-pr-496/

2021-07-13 07:38 UTC, Yeti-or approved these changes

2021-07-13 07:56 UTC, merged