fix(plasma-icons): chevron-icons updated
sberdevices/plasma pull request #555
Opened 2021-07-19 08:12 UTC by kayman233

2021-07-19 08:30 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-555/

2021-07-19 08:32 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-555/
  http://plasma.sberdevices.ru/web-storybook-pr-555/

2021-07-19 08:33 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-555/
  http://plasma.sberdevices.ru/web-pr-555/

2021-07-19 08:39 UTC, fanisco requested changes

2021-07-19 08:39 UTC, fanisco commented on packages/plasma-icons/src/Icons/IconChevronUp.tsx
> +export const IconChevronUp: React.FC<IconProps> = ({ size = 's', color, className }) => {
Тут зачем поведение поменял?

2021-07-19 09:01 UTC, kayman233 commented on packages/plasma-icons/src/Icons/IconChevronUp.tsx
> +export const IconChevronUp: React.FC<IconProps> = ({ size = 's', color, className }) => {
там иконки стали 24 на 24

2021-07-19 09:11 UTC, fanisco commented on packages/plasma-icons/src/Icons/IconChevronUp.tsx
> +export const IconChevronUp: React.FC<IconProps> = ({ size = 's', color, className }) => {
Таким образом дефолтное поведение ломается, это breaking change, не надо такого сейчас.

2021-07-19 09:30 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-555/

2021-07-19 09:34 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-555/
  http://plasma.sberdevices.ru/web-pr-555/

2021-07-19 09:35 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-555/
  http://plasma.sberdevices.ru/web-storybook-pr-555/

2021-07-19 16:52 UTC, fanisco approved these changes

2021-07-20 07:18 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-555/

2021-07-20 07:21 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-555/
  http://plasma.sberdevices.ru/web-pr-555/

2021-07-20 07:23 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-555/
  http://plasma.sberdevices.ru/web-storybook-pr-555/

2021-07-22 19:37 UTC, fanisco commented
https://github.com/sberdevices/plasma/pull/551

2021-07-22 19:37 UTC, closed without merging