chore: компонентное тестирование на cypress
sberdevices/plasma pull request #573
Opened 2021-07-26 14:24 UTC by dakhetov

2021-07-29 08:34 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-07-29 08:38 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-07-29 08:39 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-07-29 08:43 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-07-29 08:47 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-07-29 08:47 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-07-29 08:53 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-07-29 08:57 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-07-29 08:59 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-07-30 11:50 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-07-30 11:55 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-07-30 11:55 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-07-30 12:11 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-07-30 12:14 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-07-30 12:18 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-07-30 12:19 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-07-30 12:21 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-07-30 12:23 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-07-30 12:41 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-07-30 12:43 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-07-30 12:44 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-07-30 12:58 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-07-30 13:00 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-07-30 13:01 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-07-30 13:49 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-07-30 13:52 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-07-30 13:55 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-02 06:40 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-02 06:40 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-02 06:43 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-02 06:46 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-02 06:51 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-02 06:52 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-02 07:03 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-02 07:06 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-02 07:07 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-02 07:11 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-02 07:14 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-02 07:14 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-02 07:15 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-02 07:19 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-02 07:20 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-02 07:31 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-02 07:36 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-02 07:37 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-02 07:37 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-02 07:40 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-02 07:40 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-02 09:21 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-02 09:25 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-02 09:25 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-04 06:34 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-04 06:41 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-04 06:42 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-04 08:02 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-04 08:06 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-04 08:06 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-06 08:09 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-06 08:10 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-06 08:14 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-06 09:06 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-06 09:08 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-06 09:11 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-30 10:11 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-30 10:14 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-30 10:15 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-30 10:30 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-30 10:33 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-30 10:34 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-30 15:29 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-30 15:31 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-30 15:34 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-31 08:42 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-31 08:45 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-31 08:46 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-31 09:27 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-31 09:31 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-31 09:31 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-31 09:57 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-08-31 10:00 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-08-31 10:03 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-31 15:05 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-08-31 15:05 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-09-01 08:23 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-01 08:25 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-573/
  http://plasma.sberdevices.ru/web-pr-573/

2021-09-01 08:27 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-573/
  http://plasma.sberdevices.ru/web-storybook-pr-573/

2021-09-02 09:01 UTC, fanisco commented on package.json
> +    "cy:web:open-ct": "cypress open-ct --config-file cypress/config/web-config.json --env failOnSnapshotDiff=false",
Черт ногу сломит это все читать и понимать. Может имеет смысл выносить длинные команды в скрипты?

2021-09-02 09:02 UTC, fanisco commented
@OgNellis В коммитах нужно прибраться

2021-09-03 08:31 UTC, dakhetov commented on .github/workflows/cypress-ct.yml
> +      if: ${{ always() }}
это нужно для того, чтобы шаг выполнился вне зависимости от результата исполнения предыдущих. https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#always

2021-09-03 10:01 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-03 10:11 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/

2021-09-03 11:48 UTC, OgNellis commented on package.json
> +    "cy:web:open-ct": "cypress open-ct --config-file cypress/config/web-config.json --env failOnSnapshotDiff=false",
Вынес общее в отдельный скрипт, так пойдет?

2021-09-03 11:57 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-03 12:06 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/

2021-09-06 11:31 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-06 11:37 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/

2021-09-08 07:53 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-08 07:58 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/

2021-09-09 10:24 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-09 10:28 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/

2021-09-09 11:30 UTC, Yeti-or requested changes

2021-09-09 11:30 UTC, Yeti-or commented on .github/workflows/cypress-ct.yml
> +      if: ${{ always() }}
а почему их не разделить просто на две разные джобы тогда?
еще и паралельно будут исполняться

2021-09-09 11:30 UTC, Yeti-or commented on cypress/config/ui-config.json
> +        "testFiles": "**/*component.{js,jsx,ts,tsx}"
теcты на js?
у них нет суффикса типа .test.tsx или там spec.ts?

2021-09-09 11:30 UTC, Yeti-or commented on cypress/tsconfig.json
> +    "include": ["**/*.ts", "plugins/index.ts", "plugins/index.ss"]
что такое `index.ss` ??

2021-09-09 11:30 UTC, Yeti-or commented on cypress/tsconfig.json
> +    "include": ["**/*.ts", "plugins/index.ts", "plugins/index.ss"]
⚡ ⚡ ?

2021-09-09 11:30 UTC, Yeti-or commented on cypress/webpack.config.js
> +                        loader: 'babel-loader',
а мы не можем наш `.babelrc` использовать?

2021-09-09 11:30 UTC, Yeti-or commented on package.json
> +    "typescript": "4.0.3",
у нас 3.x сейчас стоит в компонентах

2021-09-09 11:30 UTC, Yeti-or commented on packages/plasma-ui/src/components/Button/Button.component.tsx
> +import React from 'react';
я бы тесты cypress писал как `Button.test.tsx` а на jest как `Button.spec.tsx` 
`.component.tsx` что-то не ясное

2021-09-09 11:42 UTC, Yeti-or commented
<img width="1225" alt="Screenshot 2021-09-09 at 14 22 05" src="https://user-images.githubusercontent.com/1813468/132679632-ce1e3f2b-f458-410f-93e4-713e02963643.png">
что-то скриншоты выгляди как-будто ничего не проверяется =/

2021-09-09 11:56 UTC, OgNellis commented on package.json
> +    "typescript": "4.0.3",
это не я, в мастере сейчас 4.0.3 оказался, ну и после ребейза ко мне попал соответственно

2021-09-09 13:22 UTC, OgNellis commented
> <img alt="Screenshot 2021-09-09 at 14 22 05" width="1225" src="https://user-images.githubusercontent.com/1813468/132679632-ce1e3f2b-f458-410f-93e4-713e02963643.png">
> 
> что-то скриншоты выгляди как-будто ничего не проверяется =/
локально выглядит корректно
<img width="1170" alt="Снимок экрана 2021-09-09 в 14 01 06" src="https://user-images.githubusercontent.com/2085343/132682020-a34c82fc-c50b-40d1-8ed1-93cc0c3dda29.png">

2021-09-09 15:10 UTC, OgNellis commented on packages/plasma-ui/src/components/Button/Button.component.tsx
> +import React from 'react';
Я за такой расклад:
`*.test.tsx` - jest тесты
`*.spec.tsx` - e2e
`*.component-test.tsx` - компонентное тестирование в cypress
последнее не хочу называть `.component.test.tsx`, потому что и визуально будем путать с просто `.test.tsx` и регулярки для тестов посложнее станут

2021-09-10 08:00 UTC, Yeti-or commented on packages/plasma-ui/src/components/Button/Button.component.tsx
> +import React from 'react';
`*.test.tsx` – jest
`*.test-e2e.tsx` – storybook + cypress ( оставить такую возможность )
`*.test-component.tsx` – cypress ( components ) -

2021-09-10 12:41 UTC, Yeti-or commented on cypress/webpack.config.js
> +                        loader: 'babel-loader',
не можем ?

2021-09-10 13:40 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-10 13:46 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/

2021-09-13 15:39 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-14 08:48 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/

2021-09-14 10:54 UTC, Yeti-or approved these changes

2021-09-14 10:54 UTC, Yeti-or commented
🎱

2021-09-14 14:09 UTC, fanisco commented on packages/plasma-web/src/components/Badge/Badge.component-test.tsx
> +const ColorThemeStyle = createGlobalStyle(light);
На это все общую обвяку не придумали, чтобы не повторять из компонента в компонент?

2021-09-14 14:09 UTC, fanisco commented on packages/plasma-ui/tsconfig.json
> +    "exclude": ["./src/helpers", "./src/showcase", "./src/**/*.stories.tsx", "**/*.test.tsx"]
а `*.component-test.tsx`?

2021-09-14 14:12 UTC, fanisco commented
Мне кажется шрифт не подтянулся
![Badge -- renders Badge snap](https://user-images.githubusercontent.com/3446303/133273782-b096d6e8-804b-4892-976a-5eb39639a6e2.png)

2021-09-15 07:16 UTC, OgNellis commented on packages/plasma-ui/tsconfig.json
> +    "exclude": ["./src/helpers", "./src/showcase", "./src/**/*.stories.tsx", "**/*.test.tsx"]
В этом конфиге убираем jest тесты, cypress остаются

2021-09-17 12:36 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-17 12:43 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/

2021-09-23 05:07 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-23 05:26 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-573/b2c-storybook/

2021-09-23 05:37 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-23 05:48 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-573/b2c-storybook/

2021-09-23 05:53 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-23 06:07 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-573/b2c-storybook/

2021-09-23 06:13 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-573/

2021-09-23 06:25 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-573/
  ui storybook: http://plasma.sberdevices.ru/pr-573/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-573/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-573/b2c-storybook/

2021-09-23 06:26 UTC, merged