feat(plasma-ui): add Slider component
sberdevices/plasma pull request #584
Opened 2021-07-29 09:31 UTC by OgNellis

2021-07-29 12:28 UTC, fanisco commented on packages/plasma-ui/package.json
> +        "typescript": "4.3.5"
Надо везде обновлять ts. Не сломает ли это совместимость?

2021-07-29 19:20 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-07-29 19:22 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-07-29 19:24 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-07-30 11:22 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-07-30 11:23 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-07-30 11:26 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-07-30 11:28 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-07-30 11:31 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-07-30 11:33 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-07-30 11:34 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-07-30 11:37 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-07-30 11:37 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-07-30 11:56 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-07-30 11:57 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-07-30 11:58 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-07-30 12:00 UTC, LamaEats requested changes

2021-08-02 14:52 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Dot.tsx
> +export const Dot = React.forwardRef<HTMLDivElement, DotProps>(
Давай не `Dot`, а `Handle`

2021-08-02 14:55 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Slider.stories.tsx
> +    const [value, setValue] = React.useState(3);
Не забудь добавить интерактив с помощью `addon-knobs`

2021-08-03 12:26 UTC, fanisco approved these changes

2021-08-03 12:26 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Handle.tsx
> +    border: ${handleBorderWidth}px solid ${surfaceLiquid03};
Сейм про `rem`

2021-08-03 12:26 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Slider.tsx
> +export const Slider: React.FC<SliderProps> = (props) => {
Нужен комментарий, он попадет в доку

2021-08-03 12:26 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Handle.tsx
> +            (_, data) => {
Можно просто запятую, пропустив первый аргумент

2021-08-03 12:26 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Handle.tsx
> +            (_, data) => {
Можно просто запятую, пропустив первый аргумент

2021-08-04 18:19 UTC, OgNellis commented on packages/plasma-ui/src/components/Slider/Handle.tsx
> +            (_, data) => {
Тайпскрипт всё-таки говорит что неможно
<img width="718" alt="Снимок экрана 2021-08-04 в 09 39 50" src="https://user-images.githubusercontent.com/2085343/128233598-2f59dafc-eaa3-4762-8134-e0c7e6dbf152.png">

2021-08-04 19:48 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-08-04 19:50 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-08-04 19:52 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-08-05 07:40 UTC, Yeti-or commented
https://github.com/sberdevices/plasma/blob/master/packages/plasma-ui/src/components/Grid/Container.tsx#L20-L33

2021-08-05 09:56 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-08-05 09:57 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-08-05 09:59 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-08-05 10:42 UTC, fanisco commented on packages/plasma-ui/package.json
> +        "@storybook/addon-controls": "6.3.6",
Он идет в пакете essentials, отдельно ставить не надо

2021-08-05 10:42 UTC, fanisco commented on packages/plasma-ui/.storybook/main.js
> +        '@storybook/addon-controls',
Нужно убрать, т.к. essentials уже есть

2021-08-05 10:42 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Double.tsx
> +import React from 'react';
Может вообще этот компонент вынести отдельно? Пусть будут отдельно Double (переименовать в Range) и Slider (который Single).
Нужно ли кому-то на ходу менять тип слайдера с одиночного круга на двойной?

2021-08-05 10:42 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Double.tsx
> +    onChangeCommitted(value: number[]): void;
onDragEnd?

2021-08-05 10:42 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Handle.tsx
> +    width: ${handleRadius * 2}rem;
Ширина зависит от радиуса контрола?

2021-08-05 11:24 UTC, OgNellis commented on packages/plasma-ui/src/components/Slider/Handle.tsx
> +    width: ${handleRadius * 2}rem;
Это ширина круга, то есть это диаметр. Ну а диаметр это два радиуса

2021-08-05 11:27 UTC, Crusader727 approved these changes
🔥

2021-08-05 11:27 UTC, OgNellis commented on packages/plasma-ui/src/components/Slider/Double.tsx
> +    onChangeCommitted(value: number[]): void;
В общем-то да, но решил не завязываться на слове "Drag". Один колбэк вызывается на изменения значения, но еще не окончательный выбор, а это уже на окончательный выбор.

Названия по образу и подобию https://material-ui.com/ru/api/slider/

2021-08-05 11:59 UTC, OgNellis commented on packages/plasma-ui/.storybook/main.js
> +        '@storybook/addon-controls',
Если удалить, то controls пропадает из вкладок с аддонами
<img width="902" alt="Снимок экрана 2021-08-05 в 13 58 28" src="https://user-images.githubusercontent.com/2085343/128346193-d3ac3a6d-df79-4e54-9a66-6b901c35c399.png">

2021-08-05 12:17 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-08-05 12:18 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-08-05 12:18 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-08-05 12:35 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Handle.tsx
> +    width: ${handleRadius * 2}rem;
Это лучше с обратной стороны рассматривать width,height => radius, везде радиус зависит от ширины. Есть какая-то потребность знать радиус контрола где-то еще?

2021-08-05 12:37 UTC, fanisco commented on packages/plasma-ui/src/components/Slider/Double.tsx
> +import React from 'react';
Думаю, что должен быть отдельный компонент Range еще по одной причине - Slider в UI - он не всегда слайдер, как в контексте этой задачи, а еще как карусель-галерея с изображениями.

2021-08-05 13:22 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-08-05 13:24 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-08-05 13:24 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-08-05 14:36 UTC, OgNellis commented on packages/plasma-ui/src/components/Slider/Double.tsx
> +import React from 'react';
С именованием range/slider неоднозначно, все по-разному называют. Нативный элемент в браузере называется range, хотя у него одно значение, логика в том, что значение можно выбрать в некотором диапазоне только.
Ты предлагаешь два значения назвать Range, а одно значение Slider? Тогда тоже остается конфликт с каруселью, но при этом у нас карусель каруселью и называется, так что проблемы не вижу.

Мне кажется логичным оставить так, потому что интерфейсы у них идентичные и по смыслу это один и тот же компонент, поведение отличается незначительно

2021-08-09 09:26 UTC, fanisco approved these changes

2021-08-09 09:26 UTC, fanisco commented on packages/plasma-ui/.storybook/main.js
> +        // '@storybook/addon-controls',
Надо убрать

2021-08-10 19:02 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-08-10 19:04 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-08-10 19:06 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-08-10 19:06 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-08-10 19:07 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-08-10 19:10 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-08-11 09:27 UTC, awinogradov approved these changes

2021-08-11 12:46 UTC, LamaEats approved these changes

2021-08-12 12:42 UTC, Yeti-or commented on docs/showcase/src/helpers/SliderSingle.tsx
> +import { Slider } from '@sberdevices/plasma-ui/components/Slider';
из корня же должно быть

2021-08-13 07:25 UTC, fanisco commented on docs/showcase/src/helpers/SliderSingle.tsx
> +import { Slider } from '@sberdevices/plasma-ui/components/Slider';
В шоукейсе и так и сяк, исторически сложилось

2021-08-18 08:16 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-08-18 08:22 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-08-18 09:28 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-08-18 09:29 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-08-18 09:30 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-08-18 10:13 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-584/

2021-08-18 10:16 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-584/
  http://plasma.sberdevices.ru/web-pr-584/

2021-08-18 10:18 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-584/
  http://plasma.sberdevices.ru/web-storybook-pr-584/

2021-08-18 10:22 UTC, merged