feat(plasma-ui, plasma-web): knobs to controls migration
sberdevices/plasma pull request #627
Opened 2021-08-09 09:47 UTC by kayman233

2021-08-09 09:56 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-627/

2021-08-09 09:57 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-627/
  http://plasma.sberdevices.ru/web-storybook-pr-627/

2021-08-09 09:58 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-627/
  http://plasma.sberdevices.ru/web-pr-627/

2021-08-09 11:43 UTC, fanisco requested changes

2021-08-09 11:43 UTC, fanisco commented on packages/plasma-ui/src/components/Badge/Badge.stories.tsx
> +export const Default: Story<any> = ({ text, size, view, contentLeft }) => (
```suggestion
export const Default: Story<BadgeProps> = ({ text, size, view, contentLeft }) => (
```

2021-08-09 11:43 UTC, fanisco commented on packages/plasma-ui/src/components/Badge/Badge.stories.tsx
> +        contentLeft={contentLeft && <IconSettings color="inherit" size="xs" />}
Тут нужно булево

2021-08-09 21:49 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-627/

2021-08-09 21:54 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-627/
  http://plasma.sberdevices.ru/web-storybook-pr-627/

2021-08-09 21:54 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-627/
  http://plasma.sberdevices.ru/web-pr-627/

2021-08-11 18:35 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-627/

2021-08-11 18:36 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-627/
  http://plasma.sberdevices.ru/web-pr-627/

2021-08-11 18:39 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-627/
  http://plasma.sberdevices.ru/web-storybook-pr-627/

2021-08-11 22:42 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-627/

2021-08-11 22:43 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-627/
  http://plasma.sberdevices.ru/web-storybook-pr-627/

2021-08-11 22:44 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-627/
  http://plasma.sberdevices.ru/web-pr-627/

2021-08-12 09:53 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-627/

2021-08-12 09:56 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-627/
  http://plasma.sberdevices.ru/web-storybook-pr-627/

2021-08-12 09:56 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-627/
  http://plasma.sberdevices.ru/web-pr-627/

2021-08-12 19:52 UTC, fanisco commented on packages/plasma-ui/src/helpers/disableProps.tsx
> +export const disableProps = (props: string[]) => {
Добавить JSDoc, что он делает

2021-08-12 19:56 UTC, fanisco commented on packages/plasma-ui/src/components/Button/Button.stories.tsx
> +const Action_ButtonPropsToDisable = ['text', 'tabIndex', 'square', 'focused', 'outlined', 'stretch'];
Переменную с маленькой буквы, андерскор тут не нужен. Андерскор нужен только для того, чтобы компонент со стори не конфликтовал

2021-08-12 20:00 UTC, fanisco commented on packages/plasma-ui/src/components/Button/Button.stories.tsx
> +    enableIcon: true,
Не работает =(

2021-08-12 20:03 UTC, fanisco commented
@kayman233 в целом мне все нравится, только, мне кажется, ты забыл про web - или ты отдельным заходом сделаешь  то же самое для этой либы?
И добавляй, пожалуйста, в описание, какие компоненты ты затронул

2021-08-12 20:04 UTC, kayman233 commented on packages/plasma-ui/src/components/Button/Button.stories.tsx
> +    enableIcon: true,
а что именно не работает?

2021-08-12 20:04 UTC, kayman233 commented
> @kayman233 в целом мне все нравится, только, мне кажется, ты забыл про web - или ты отдельным заходом сделаешь то же самое для этой либы?
> И добавляй, пожалуйста, в описание, какие компоненты ты затронул

Да, отдельным заходом буду web делать после ui

2021-08-16 07:56 UTC, fanisco approved these changes

2021-08-17 12:10 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-627/

2021-08-17 12:12 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-627/
  http://plasma.sberdevices.ru/web-storybook-pr-627/

2021-08-17 12:14 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-627/
  http://plasma.sberdevices.ru/web-pr-627/

2021-08-18 06:32 UTC, Yeti-or commented on packages/plasma-ui/src/components/Image/Image.stories.tsx
> +export const Basic: Story<ImageProps> = ({ base }) => (
Кажется нам тут хватит одной стори, и нужно добавить в неё контрол на ratio

2021-08-18 08:08 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-627/

2021-08-18 08:11 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-627/
  http://plasma.sberdevices.ru/web-pr-627/

2021-08-18 08:12 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-627/
  http://plasma.sberdevices.ru/web-storybook-pr-627/

2021-08-18 13:47 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-627/

2021-08-18 13:50 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-627/
  http://plasma.sberdevices.ru/web-pr-627/

2021-08-18 13:51 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-627/
  http://plasma.sberdevices.ru/web-storybook-pr-627/

2021-08-18 13:51 UTC, merged