chore(plasma-ui, plasma-web): knobs to controls migration - web - part 1
sberdevices/plasma pull request #651
Opened 2021-08-18 21:56 UTC by kayman233

Web: 

- Button
- Carousel
- Checkbox
- Modal

2021-08-18 22:02 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-651/

2021-08-18 22:05 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-651/
  http://plasma.sberdevices.ru/web-storybook-pr-651/

2021-08-18 22:07 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-651/
  http://plasma.sberdevices.ru/web-pr-651/

2021-08-19 07:58 UTC, fanisco requested changes

2021-08-19 07:58 UTC, fanisco commented on packages/plasma-web/src/components/Button/Button.stories.tsx
> +    'circle-square',
Button:pin=circle-square вызывает ошибку, видимо неправильное значение

2021-08-19 07:58 UTC, fanisco commented on packages/plasma-web/src/components/Button/Button.stories.tsx
> +    'square-circle',
Тоже падает

2021-08-19 13:21 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-651/

2021-08-19 13:25 UTC, SberDevices-Eva commented
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-651/
  http://plasma.sberdevices.ru/web-storybook-pr-651/

2021-08-19 13:25 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-651/
  http://plasma.sberdevices.ru/web-pr-651/

2021-08-20 08:26 UTC, fanisco approved these changes

2021-09-03 08:19 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-651/

2021-09-03 08:27 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-651/
  ui storybook: http://plasma.sberdevices.ru/pr-651/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-651/web-storybook/

2021-09-07 17:58 UTC, Yeti-or commented on packages/plasma-web/src/components/Checkbox/Checkbox.stories.tsx
>  export default {
![Uploading Screenshot 2021-09-07 at 20.57.52.png…]()

А почему дефолтная не переводена?

2021-09-07 18:48 UTC, Yeti-or approved these changes

2021-09-07 18:48 UTC, Yeti-or commented on packages/plasma-web/src/components/Modal/Modal.stories.tsx
> +    title: 'Controls/Modal',
а весь остальной текст давай тоже запихаем

2021-09-07 18:48 UTC, Yeti-or commented on packages/plasma-web/src/components/Checkbox/Checkbox.stories.tsx
>  export default {
![Uploading Screenshot 2021-09-07 at 20.57.52.png…]()

2021-09-07 18:48 UTC, Yeti-or commented on packages/plasma-web/src/components/Checkbox/Checkbox.stories.tsx
>  export default {
<img width="1038" alt="Screenshot 2021-09-07 at 20 57 52" src="https://user-images.githubusercontent.com/1813468/132393379-017b9f19-b214-4dd3-81a9-fad915a23c11.png">

2021-09-08 22:17 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-651/

2021-09-08 22:18 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-651/

2021-09-08 22:25 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-651/
  ui storybook: http://plasma.sberdevices.ru/pr-651/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-651/web-storybook/

2021-09-09 11:43 UTC, Yeti-or commented
🆗

2021-09-09 12:00 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-651/

2021-09-09 12:05 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-651/
  ui storybook: http://plasma.sberdevices.ru/pr-651/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-651/web-storybook/

2021-09-09 12:09 UTC, merged