feat: Added Plasma Temple documentation app
sberdevices/plasma pull request #918
Opened 2021-11-08 13:53 UTC by fanisco

2021-11-08 14:34 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-918/

2021-11-08 14:49 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-918/
  ui storybook: http://plasma.sberdevices.ru/pr-918/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-918/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-918/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-918/temple-storybook/

2021-11-10 10:33 UTC, kvpolyanskiy approved these changes

2021-11-10 15:55 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-918/

2021-11-10 16:15 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-918/
  ui storybook: http://plasma.sberdevices.ru/pr-918/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-918/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-918/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-918/temple-storybook/

2021-11-11 08:49 UTC, VladislavPetyukevich approved these changes

2021-11-16 08:55 UTC, LamaEats requested changes
немного съехали таблички пропсов в core.md в разделах PlasmaApp и Компонент экрана

Навигационная табличка внизу доки не нужна, дропни ее плиз

2021-11-16 11:17 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-918/

2021-11-16 11:36 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-918/
  ui storybook: http://plasma.sberdevices.ru/pr-918/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-918/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-918/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-918/temple-storybook/

2021-11-16 13:35 UTC, LamaEats approved these changes

2021-11-16 14:19 UTC, merged