fix(plasma-web): prevent disabled select from opening
sberdevices/plasma pull request #925
Opened 2021-11-15 15:51 UTC by IArny

Исправлено открытие отключенного Select при нажатии на стрелочку в chrome
<img width="349" alt="изображение" src="https://user-images.githubusercontent.com/42856876/141812155-2db0af32-a9b7-4717-804e-7733bcb5679b.png">

2021-11-15 16:01 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-925/

2021-11-15 16:16 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-925/
  ui storybook: http://plasma.sberdevices.ru/pr-925/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-925/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-925/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-925/temple-storybook/

2021-11-16 06:53 UTC, neretin-trike approved these changes

2021-11-16 07:38 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-925/

2021-11-16 07:54 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-925/
  ui storybook: http://plasma.sberdevices.ru/pr-925/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-925/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-925/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-925/temple-storybook/

2021-11-16 08:40 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-925/

2021-11-16 08:42 UTC, fanisco requested changes

2021-11-16 08:42 UTC, fanisco commented on packages/plasma-web/src/components/Select/SelectView.tsx
> +                    disabled={disabled}
Не хватает того же самого для packages/plasma-b2c/src/components/Select/SelectView.tsx

2021-11-16 08:53 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-925/
  ui storybook: http://plasma.sberdevices.ru/pr-925/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-925/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-925/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-925/temple-storybook/

2021-11-16 08:58 UTC, IArny commented on packages/plasma-web/src/components/Select/SelectView.tsx
> +                    disabled={disabled}
Нужно сначала собрать web, обновить его в b2c, и потом можно будет в b2c добавить disabled

2021-11-16 09:15 UTC, fanisco commented on packages/plasma-web/src/components/Select/SelectView.tsx
> +                    disabled={disabled}
Все можно сделать в рамках одного PR. У b2c и web два разных независимых друг от друга SelectView

2021-11-16 09:28 UTC, IArny commented on packages/plasma-web/src/components/Select/SelectView.tsx
> +                    disabled={disabled}
Да, SelectView независимые, но параметр передается в SelectDropdown, который как раз из web

2021-11-16 11:19 UTC, fanisco commented on packages/plasma-web/src/components/Select/SelectView.tsx
> +                    disabled={disabled}
Все еще не вижу причины по которой все нельзя сделать в одном PR =)
Может стоит попробовать локально выполнить `npx lerna bootstrap`

2021-11-16 12:39 UTC, IArny commented on packages/plasma-web/src/components/Select/SelectView.tsx
> +                    disabled={disabled}
Ок, спасибо

2021-11-16 13:47 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-925/

2021-11-16 13:57 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-925/
  ui storybook: http://plasma.sberdevices.ru/pr-925/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-925/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-925/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-925/temple-storybook/

2021-11-16 14:23 UTC, fanisco commented on packages/plasma-web/src/components/Select/Select.component-test.tsx
> +        cy.get('button svg').click();
какой-то странный селектор для клика @Yeti-or @dakhetov

2021-11-16 14:25 UTC, dakhetov commented on packages/plasma-web/src/components/Select/Select.component-test.tsx
> +        cy.get('button svg').click();
Тут получается, что мы кликаем не на кнопку, а на svg внутри кнопки, если в этом и был смысл, то вполне нормально.

2021-11-16 14:34 UTC, IArny commented on packages/plasma-web/src/components/Select/Select.component-test.tsx
> +        cy.get('button svg').click();
Там баг воспроизводился при клике по стрелке

2021-11-16 14:45 UTC, IArny commented
Баг воспроизводился при клике на стрелку селекта - при отключенном (disabled) состоянии список все равно раскрывался (воспроизводилось в chrome)

2021-11-16 14:55 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-925/

2021-11-16 14:56 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-925/

2021-11-16 15:07 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-925/
  ui storybook: http://plasma.sberdevices.ru/pr-925/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-925/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-925/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-925/temple-storybook/

2021-11-16 15:11 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-925/
  ui storybook: http://plasma.sberdevices.ru/pr-925/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-925/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-925/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-925/temple-storybook/

2021-11-17 05:05 UTC, fanisco commented on packages/plasma-web/cypress.json
> +{}
Зачем этот файл?

2021-11-17 05:05 UTC, fanisco commented on packages/plasma-web/src/components/Select/Select.component-test.tsx
> +        cy.get('button svg').click();
Достаточно клика по `button`

2021-11-17 11:21 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-925/

2021-11-17 11:35 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-925/
  ui storybook: http://plasma.sberdevices.ru/pr-925/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-925/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-925/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-925/temple-storybook/

2021-11-17 12:10 UTC, fanisco approved these changes

2021-11-18 12:39 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-925/

2021-11-18 12:57 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-925/
  ui storybook: http://plasma.sberdevices.ru/pr-925/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-925/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-925/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-925/temple-storybook/

2021-11-18 13:02 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-925/

2021-11-18 13:05 UTC, merged

2021-11-18 13:20 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-925/
  ui storybook: http://plasma.sberdevices.ru/pr-925/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-925/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-925/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-925/temple-storybook/