feat: checkbox label type
sberdevices/plasma pull request #945
Opened 2021-11-19 16:09 UTC by takovoy

Хотелось бы свой контент в лейбл у чекбокса вставлять, вот пример
![Screenshot 2021-11-19 at 19 09 00](https://user-images.githubusercontent.com/7758731/142654489-b4d373c6-e82e-49f8-b728-4b9ac8cfc984.png)

2021-11-19 16:23 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-945/

2021-11-19 16:38 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-945/
  ui storybook: http://plasma.sberdevices.ru/pr-945/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-945/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-945/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-945/temple-storybook/

2021-11-22 07:59 UTC, kayman233 requested changes

2021-11-22 07:59 UTC, kayman233 commented on packages/plasma-core/src/components/Basebox/Basebox.tsx
> +    label?: React.ReactNode;
```suggestion
    label?: string | number | React.ReactNode;
```
наверное лучше так, чтобы было по аналогии с description. Кстати, а чем не подходит description для таких целей?

2021-11-22 08:35 UTC, fanisco requested changes

2021-11-22 08:35 UTC, fanisco commented on packages/plasma-core/src/components/Basebox/Basebox.tsx
> +    label?: React.ReactNode;
Дизайнерами одобрено?

2022-01-12 12:38 UTC, closed without merging