feat: Add worflow_run for documentation action
sberdevices/plasma pull request #948
Opened 2021-11-23 05:40 UTC by neretin-trike

2021-11-23 05:51 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 06:04 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 06:22 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 06:24 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 06:44 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 07:08 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 07:09 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 07:26 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 07:51 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 09:33 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 09:35 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 10:26 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 10:45 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 11:04 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 12:14 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-23 12:34 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-11-24 08:56 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-24 09:15 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-11-24 11:45 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-24 12:09 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-11-25 05:58 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 05:59 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 06:01 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 06:05 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 06:16 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 06:21 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 06:22 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 06:33 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 07:11 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 07:49 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 08:40 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-25 08:44 UTC, fanisco commented on .github/workflows/release.yml
> +      ARTIFACT_NAME: ${{ github.event_name != 'pull_request' && 'next' ||  format('pr-{0}', github.event.number) }}
🤯

2021-11-25 08:44 UTC, fanisco commented on .github/workflows/release.yml
> +          key: ${{ github.sha }}
Тут для чего восстанавливаешь?

2021-11-25 08:44 UTC, fanisco commented on .github/workflows/release.yml
> +          key: ${{ github.sha }}
Тут из чего восстанавливаешь?

2021-11-25 08:44 UTC, fanisco commented on .github/workflows/release.yml
> +          cp -R ./website/plasma-ui-docs/build ../build/${ARTIFACT_NAME}/ui
Тут задубливания слешей не будет? Юниксы такое съедят?

2021-11-25 08:44 UTC, fanisco commented on .github/workflows/release.yml
> +        if: github.event_name == 'pull_request'
👍

2021-11-25 08:44 UTC, fanisco commented on .github/workflows/release.yml
> +    needs: release
👍

2021-11-25 08:45 UTC, fanisco commented on .github/workflows/release.yml
> +      ARTIFACT_NAME: ${{ github.event_name != 'pull_request' && 'next' ||  format('pr-{0}', github.event.number) }}
Но тернарник сюда подходит лучше

2021-11-25 09:03 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-11-25 09:21 UTC, neretin-trike commented on .github/workflows/release.yml
> +      ARTIFACT_NAME: ${{ github.event_name != 'pull_request' && 'next' ||  format('pr-{0}', github.event.number) }}
ага, но yml не поддерживает его, поэтому так

2021-11-25 09:24 UTC, neretin-trike commented on .github/workflows/release.yml
> +          key: ${{ github.sha }}
тут происходит кеширование итогового результата (с учётом релиза и т.д.)

2021-11-25 09:24 UTC, neretin-trike commented on .github/workflows/release.yml
> +          key: ${{ github.sha }}
а здесь восстанавливаю из кеша, который собрался на предыдущей джобе

2021-11-25 09:26 UTC, neretin-trike commented on .github/workflows/release.yml
> +          cp -R ./website/plasma-ui-docs/build ../build/${ARTIFACT_NAME}/ui
а вроде не должно быть. В ARTIFACT_NAME попадает либо `next`, либо `pr-000`, без слешей

2021-11-29 09:01 UTC, fanisco commented
@neretin-trike предварительно - ОК, но у тебя висит Publish в проверках

2021-11-29 11:23 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-11-29 11:45 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-12-01 08:03 UTC, fanisco requested changes

2021-12-01 08:03 UTC, fanisco commented on .github/workflows/release.yml
> -  publish:
Давай раз уж в защите ветки идет переименование, то и здесь переименуем. Т.к. тут у нас выполняется несколько задач, предлагаю переименовать файл и имя (1 строка) в `ci` и `CI` или `main-ci ` и `Main CI`

2021-12-01 09:04 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-01 09:21 UTC, fanisco commented on .github/workflows/main-ci.yml
> +            mv next current
В пуллреквесте не заливается билд?

2021-12-01 09:25 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-12-01 09:26 UTC, neretin-trike commented on .github/workflows/main-ci.yml
> +            mv next current
это происходит в степе `Clean old builds` перед `Upload builds`. Честно, не знаю почему так было сделано в воркфлоу документации, но решил не ломать работающую логику

2021-12-01 09:37 UTC, fanisco commented on .github/workflows/main-ci.yml
> +      - name: Clean old builds
Clean old PR builds

2021-12-01 09:37 UTC, fanisco commented on .github/workflows/main-ci.yml
> +      - name: Upload builds
Upload PR or master builds

2021-12-01 09:37 UTC, fanisco commented on .github/workflows/main-ci.yml
> +      - name: Update and clean documentation
Clean and update master build

2021-12-02 09:48 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-02 10:13 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-12-03 13:23 UTC, fanisco requested changes

2021-12-03 13:23 UTC, fanisco commented on .github/workflows/main-ci.yml
> +      # Удаляет предыдущие PR билды
По коду это и так понятно, но не понятно будет почему именно так

2021-12-03 13:23 UTC, fanisco commented on .github/workflows/main-ci.yml
> +      # Загружает текущие версии билдов
Сейм

2021-12-03 13:23 UTC, fanisco commented on .github/workflows/main-ci.yml
> +      # Удаляет предыдущие версии master билдов и устанавливает текущие
Сейм

2021-12-03 13:25 UTC, fanisco requested changes

2021-12-03 13:25 UTC, fanisco commented on .github/workflows/main-ci.yml
> +      - name: Cache out build packages
```suggestion
      - name: Restore build packages from cache
```

2021-12-03 13:25 UTC, fanisco commented on .github/workflows/main-ci.yml
> +        id: restore-build
```suggestion
        id: cache-build
```

2021-12-03 13:25 UTC, fanisco commented on .github/workflows/main-ci.yml
> +      # Кеширование итогового результата с учётом обновлённых версий пакетов
Кеширование всей файловой структуры

2021-12-06 05:56 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-06 06:18 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-12-06 20:52 UTC, Yeti-or commented on .github/workflows/main-ci.yml
> +          key: ${{ github.sha }}
он перетрется же при пересборке ?

2021-12-06 20:52 UTC, Yeti-or commented on .github/workflows/main-ci.yml
> +          cp -R ./website/plasma-website/build ../build/${ARTIFACT_NAME}
два вопроса:
1) мы не можем запустить это всё в паралель?:

lerna run build --scope="@sberdevices/plasma-website" --scope="./website/plasma-ui-docs" итп  --no-bail  --stream --parallel --concurrency ?

2) нам обязательно делать cp ? мы не можем собирать сразу в ../build ? storybook вроде принимает параметр output сборка наверняка тоже, а то гоняем туда сюда, сборка и так  чувствую долгая будет
ну или как вариант можем собирать куда собирается а потом просто ln -s сделать? или так ничего не по ssh не скопируется?

2021-12-06 20:52 UTC, Yeti-or commented on .github/workflows/main-ci.yml
> +      # (pull_request или push), его необходимо выполнить до или после удаления билдов
написано что есть зависимость от типа шага, при это if не вижу; почему так?

2021-12-06 21:23 UTC, fanisco commented on .github/workflows/main-ci.yml
> +          key: ${{ github.sha }}
При пересборке - в смысле при следующем коммите в релизе? Проверял - список коммитов не обновляется в рамках одного воркфлоу

2021-12-06 21:23 UTC, fanisco commented on .github/workflows/main-ci.yml
> +          key: ${{ github.sha }}
@neretin-trike тут бы перепроверить меня, конечно

2021-12-07 04:48 UTC, neretin-trike commented on .github/workflows/main-ci.yml
> +          key: ${{ github.sha }}
если я правильно вас понял, то вроде не должен, т.к. тогда в следующей джобе по этому ключу кеш не искался бы

2021-12-07 04:50 UTC, neretin-trike commented on .github/workflows/main-ci.yml
> +          cp -R ./website/plasma-website/build ../build/${ARTIFACT_NAME}
ну в данной задачке, которую я делаю, необходимо было вынести документацию за релиз. По оптимизации всего воркфлоу (а эти шаги чуть ли не самые медленные) у нас отдельная таска есть, поэтому я бы хотел эти идеи проверить уже там

2021-12-07 04:52 UTC, neretin-trike commented on .github/workflows/main-ci.yml
> +      # (pull_request или push), его необходимо выполнить до или после удаления билдов
просто if'ы идут в шагах Clean old PR builds (до) публикации и в Clean and update master builds публикации. А по факту - этот шаг по среди между ними, поэтому так и описал

2021-12-07 07:39 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-07 10:23 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-07 11:28 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-07 12:25 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-08 04:51 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-08 05:30 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-08 06:23 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-08 06:46 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-12-08 07:39 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-08 08:07 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-08 08:27 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-12-08 09:45 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-08 10:10 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-12-09 08:04 UTC, fanisco approved these changes

2021-12-09 08:04 UTC, fanisco commented
🤞

2021-12-10 09:05 UTC, neretin-trike commented on .github/workflows/main-ci.yml
> +          cp -R ./website/plasma-website/build ../build/${ARTIFACT_NAME}
как в итоге сделал:
1. Распраллелил шаги по сборке документации и сторибуков. На каждый шаг выделяется 4 потока (предположительно), но при этом они сами идут последовательно
2. Конкретных параметров `outup` я не обнаружил, но даже если бы они были, не получилось бы разделить по конкретным папкам, т.к. несколько билдов. Поэтому использовал вместо `cp` -> `mv`. По сути он просто меняет указатель в файловой системе на другой путь и это практически не занимает время

2021-12-12 23:36 UTC, Yeti-or approved these changes

2021-12-12 23:36 UTC, Yeti-or commented on package.json
> +    "concurrently": "6.4.0",
а это зачем ?

2021-12-13 04:27 UTC, neretin-trike commented on package.json
> +    "concurrently": "6.4.0",
блин, забыл снести :C

2021-12-13 04:46 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-948/

2021-12-13 05:12 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-948/
  ui storybook: http://plasma.sberdevices.ru/pr-948/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-948/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-948/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-948/temple-storybook/

2021-12-13 05:31 UTC, merged