feat: Add breaWord prop for `Typography` components
sberdevices/plasma pull request #962
Opened 2021-12-01 06:20 UTC by neretin-trike

2021-12-01 06:30 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-962/

2021-12-01 06:45 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-962/
  ui storybook: http://plasma.sberdevices.ru/pr-962/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-962/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-962/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-962/temple-storybook/

2021-12-01 07:13 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-962/

2021-12-01 07:29 UTC, Yeti-or commented on packages/plasma-core/src/components/Typography/Typography.component-test.tsx
> +                    <Body1 disableBreakWord>Hello Body 1</Body1>
а v2 мы будем писать 
`disableBreakword=false` ?

2021-12-01 07:29 UTC, Yeti-or commented on packages/plasma-core/src/components/Typography/Typography.component-test.tsx
> +                    <Body1 disableBreakWord>Hello Body 1</Body1>
может добавить проп:
```
<Body1 breakWord={false}>Hello Body 1</Body1>
```
сейчас некрасиво но потом мы его просто сделаем дополнительным
```
<Body1 breakWord>Hello Body 1</Body1>
```

2021-12-01 07:32 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-962/
  ui storybook: http://plasma.sberdevices.ru/pr-962/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-962/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-962/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-962/temple-storybook/

2021-12-01 08:03 UTC, neretin-trike commented on packages/plasma-core/src/components/Typography/Typography.component-test.tsx
> +                    <Body1 disableBreakWord>Hello Body 1</Body1>
вообще думал, что в v2 переименуем в `enableBreakWord` где необходимо переносить. Но твой вариант больше подходит, спасиб 👌

2021-12-02 06:14 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-962/

2021-12-02 06:27 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-962/
  ui storybook: http://plasma.sberdevices.ru/pr-962/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-962/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-962/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-962/temple-storybook/

2021-12-02 13:13 UTC, fanisco requested changes

2021-12-02 13:13 UTC, fanisco commented on packages/plasma-core/src/mixins/applyHyphens.ts
> +const enabledBreakWord = css`
А зачем отдельная переменная? Пусть будет внутри миксина. В твоем случае тут матрешка `css(css(...))`

2021-12-03 03:29 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-962/

2021-12-03 03:39 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-962/
  ui storybook: http://plasma.sberdevices.ru/pr-962/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-962/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-962/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-962/temple-storybook/

2021-12-03 07:39 UTC, fanisco requested changes

2021-12-03 07:39 UTC, fanisco commented on packages/plasma-core/src/mixins/applyHyphens.ts
> +    hyphens: auto;`}
```suggestion
export const applyHyphens: InterpolationFunction<BreakWordProps> = ({ breakWord = true }) =>
    breakWord &&
    css`
        overflow-wrap: break-word;
        hyphens: auto;
    `;
```

2021-12-03 07:44 UTC, neretin-trike commented on packages/plasma-core/src/mixins/applyHyphens.ts
> +    hyphens: auto;`}
:С

2021-12-03 09:22 UTC, neretin-trike commented on packages/plasma-core/src/mixins/applyHyphens.ts
> +    hyphens: auto;`}
так, погоди. При таком подходе будет проблема, потому что тип возвращаемой функции превращается в `false | FlattenSimpleInterpolation`. И если breakWord принудительно отключен, то в css шаблоне, где используется миксин, будет возвращаться false

2021-12-03 13:57 UTC, fanisco commented on packages/plasma-core/src/mixins/applyHyphens.ts
> +    hyphens: auto;`}
И пускай, оно так везде работает https://github.com/sberdevices/plasma/blob/master/packages/plasma-core/src/mixins/applyScrollSnap.ts https://github.com/sberdevices/plasma/blob/master/packages/plasma-core/src/mixins/applyMaxLines.ts https://github.com/sberdevices/plasma/blob/master/packages/plasma-core/src/mixins/addFocus.ts#L84

2021-12-03 14:41 UTC, neretin-trike commented on packages/plasma-core/src/mixins/applyHyphens.ts
> +    hyphens: auto;`}
это странно на самом деле, но окей

2021-12-06 05:22 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-962/

2021-12-06 05:40 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-962/
  ui storybook: http://plasma.sberdevices.ru/pr-962/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-962/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-962/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-962/temple-storybook/

2021-12-06 08:16 UTC, Yeti-or approved these changes

2021-12-07 20:27 UTC, fanisco approved these changes

2021-12-09 06:08 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-962/

2021-12-09 06:20 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-962/
  ui storybook: http://plasma.sberdevices.ru/pr-962/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-962/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-962/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-962/temple-storybook/

2021-12-09 12:55 UTC, Yeti-or approved these changes

2021-12-09 12:55 UTC, merged