feat(plasma-core): Add ReactNode type for label field in `Checkbox` component
sberdevices/plasma pull request #969
Opened 2021-12-06 10:57 UTC by neretin-trike

2021-12-06 11:08 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-969/

2021-12-06 11:20 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-969/
  ui storybook: http://plasma.sberdevices.ru/pr-969/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-969/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-969/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-969/temple-storybook/

2021-12-06 20:57 UTC, Yeti-or approved these changes

2021-12-06 21:21 UTC, fanisco requested changes

2021-12-06 21:21 UTC, fanisco commented on packages/plasma-core/src/components/Basebox/Basebox.tsx
> +    label?: string | number | React.ReactNode;
`string | number` здесь избыточны, они уже включены в `ReactNode`

2021-12-07 05:05 UTC, neretin-trike commented on packages/plasma-core/src/components/Basebox/Basebox.tsx
> +    label?: string | number | React.ReactNode;
оке, для description так же сделал

2021-12-07 05:22 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-969/

2021-12-07 05:36 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-969/
  ui storybook: http://plasma.sberdevices.ru/pr-969/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-969/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-969/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-969/temple-storybook/

2021-12-07 09:33 UTC, fanisco approved these changes

2021-12-09 06:52 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-969/

2021-12-09 07:03 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-969/
  ui storybook: http://plasma.sberdevices.ru/pr-969/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-969/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-969/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-969/temple-storybook/

2021-12-10 08:13 UTC, OgNellis approved these changes

2021-12-15 04:59 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-969/

2021-12-15 05:12 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-969/
  ui storybook: http://plasma.sberdevices.ru/pr-969/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-969/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-969/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-969/temple-storybook/

2021-12-15 05:13 UTC, merged