feat(plasma-b2c): Add mobile sizes for Tabs
sberdevices/plasma pull request #972
Opened 2021-12-08 06:00 UTC by IArny

Добавлены размеры для Табов на маленьких экранах 
https://www.figma.com/file/fOjKwOzEasaagxuQi4JN0W/%F0%9F%8C%80Playground-Web-B2C?node-id=2556%3A7768
https://www.figma.com/file/gfdZsoobDtlKmDNslGYN2S/Visper?node-id=19690%3A16623

2021-12-08 06:15 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-08 06:16 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-08 06:25 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-08 06:31 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-08 07:56 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-08 08:10 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-08 08:28 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-08 08:45 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-08 09:19 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-08 09:35 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-09 10:00 UTC, neretin-trike approved these changes

2021-12-09 10:21 UTC, Yeti-or requested changes

2021-12-09 10:27 UTC, IArny commented on packages/plasma-b2c/src/components/Tabs/Tabs.tsx
> +            --tabs-height: 2.5rem;
да, все так

2021-12-09 10:29 UTC, IArny commented on packages/plasma-b2c/src/components/Tabs/Tabs.tsx
> +            --tabs-height: 2.5rem;
да, на всем что меньше 959 будут меньше табы

2021-12-09 13:24 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-09 13:30 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-15 08:57 UTC, fanisco requested changes

2021-12-15 08:57 UTC, fanisco commented on packages/plasma-b2c/src/components/Tabs/Tabs.tsx
> +const sizes = {
Не хватает комментария

2021-12-15 08:57 UTC, fanisco commented
@IArny не хватает визуальных тестов на добавленный функционал

2021-12-15 10:01 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-15 10:17 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-15 11:59 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-15 12:13 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-16 09:32 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-16 09:43 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-16 11:09 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-16 11:23 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-16 11:28 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-16 11:40 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-16 11:44 UTC, fanisco approved these changes

2021-12-16 11:52 UTC, Yeti-or commented on packages/plasma-core/src/components/Tabs/Tabs.component-test.tsx
> +describe('plasma-b2c: Tabs', () => {
стоп а почему b2c ?
@fanisco у нас size в в оставльных либах не нужен ?

если не нужен и это только для b2c то нужно перенести  тест про size в папку
packages/plasma-b2c/src/components/Tabs/Tabs.component-test.tsx

если это нужно для всех то перенести сам код в core

2021-12-16 11:56 UTC, IArny commented on packages/plasma-core/src/components/Tabs/Tabs.component-test.tsx
> +describe('plasma-b2c: Tabs', () => {
Не увидел, что там симлинк, щас верну как было

2021-12-16 11:57 UTC, fanisco commented on packages/plasma-core/src/components/Tabs/Tabs.component-test.tsx
> +describe('plasma-b2c: Tabs', () => {
@IArny перенеси тест в папку компонента в b2c

2021-12-16 12:16 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-16 12:28 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-16 12:43 UTC, SberDevices-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-972/

2021-12-16 12:52 UTC, SberDevices-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-972/
  ui storybook: http://plasma.sberdevices.ru/pr-972/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-972/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-972/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-972/temple-storybook/

2021-12-16 13:22 UTC, Yeti-or approved these changes

2021-12-16 13:25 UTC, OgNellis approved these changes

2021-12-16 13:52 UTC, fanisco approved these changes

2021-12-16 13:56 UTC, dakhetov approved these changes

2021-12-16 13:58 UTC, merged